# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35687403aea472bdcd77c4d3bcd419a30987df502078fb6f62513ce0c20fae77b1839051d3b575cf6f44532562bef26840454baf1ecbcc446f74eef004d8763b

test:
  secret_key_base: 018dc2ef77235c498bb42f6719a3a12d88e6b5b34fdc9155171f8534a82a29ed95094fc3524f310e5873ed139e4a1e785578ebb46fbc07e0c5e08b742e07dc19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
